### ISSUE TITLE
cannot unmarshal 1w

### ISSUE THREAD

**Issue by jmnote** [kuoss/venti#174]
```
time="2025-03-04T05:36:36Z" level=error msg="application error: failed to initialize services: new alertRuleService err: loadAlertRuleFileFromFilename err: unmarshalStrict err: yaml: unmarshal errors:\n  line 354: cannot unmarshal !!str `1w` into time.Duration" file="proc.go:271"
```

```yaml
  # You may want to increase the alert manager 'repeat_interval' for this type of alert to daily or weekly
  - alert: HostCpuIsUnderutilized
    expr: (min by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1h]))) > 0.8
    for: 1w
    labels:
      severity: info
    annotations:
      summary: Host CPU is underutilized (instance {{ $labels.instance }})
      description: "CPU load has been < 20% for 1 week. Consider reducing the number of CPUs.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

https://samber.github.io/awesome-prometheus-alerts/rules#rule-host-and-hardware-1-15
