### ISSUE TITLE
datasourceSelector spec

### ISSUE THREAD

**Issue by jmnote** [kuoss/venti#42]
초안
```yaml
datasourceSelector:
  isMain: # true, false, all*
  type:   # prometheus, lethe, all*
```
```yaml
datasourceSelector:
  system: # main, sub, all*
  type:   # prometheus, lethe, all*
```

참고자료
- https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
- https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/
- https://learn.microsoft.com/en-us/advertising/scripts/reference/labelselector
- https://javadoc.jenkins.io/plugin/openshift-client/com/openshift/jenkins/plugins/freestyle/model/ResourceSelector.html
- https://github.com/openshift/jenkins-client-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/freestyle/model/ResourceSelector.java#L20-L29
