### ISSUE TITLE
field aggregation not found in type model.Target

### ISSUE THREAD

**Issue by jmnote** [kuoss/venti#68]
time="2023-05-25T08:04:14Z" level=warning msg="Warning: error on loadDashboardFromFile(skipped): error on UnmarshalStrict: yaml: unmarshal errors:\n  line 12: field aggregation not found in type model.Target"

```yaml
title: Target Clusters
rows:
- panels:
  - title: target clusters info
    type: multitable
    headers: ["target","k8s","container runtime","kernel","kubelet","kubeproxy","os"]
    targets:
    - expr: kubernetes_build_info{job="kubernetes-apiservers"}
      legends: ["{{git_version}}"]
    - expr: kube_node_info
      legends: ["{{container_runtime_version}}","{{kernel_version}}","{{kubelet_version}}", "{{kubeproxy_version}}","{{os_image}}"]
      aggregation: first ###
```
