### ISSUE TITLE
datatsource discovery

### ISSUE THREAD

**Issue by jmnote** [kuoss/venti#8]
service annotations
```
kind: Service
metadata:
  annotations:
    kuoss.org/datasource: "prometheus" // prometheus, lethe
```

port 결정
- 서비스에 port가 하나이면 그 port 사용
- 서비스에 port가 둘 이상인데
  - 이름이 `http`인 port가 있으면 그 port 사용
  - 없으면 첫번째 port 사용

```
datasources:
  discovery:
    enabled: true
    defaultNamespace: kuoss
    annotationKey: "kuoss.org/datasource"
    byNamePrometheus: true
    byNameLethe: true
```
